### ISSUE TITLE
Error en comando node 03.first-io.js

### ISSUE THREAD

**Issue by JohnJasso** [UG-InternetApps/Tareas#5]
Buenas noches,

¿A alguien le ha pasado? 

Completé mi script reemplazando el archivo de prueba test.txt por _process.argv[2]_, y quise probarlo usando el comando `node 03.first-io.js` pero me arrojaba un error:

```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/Users/GryffinclawJohn/Documents/FIMEE/13 - 8vo Semestre/Aplicaciones de Internet/Development/NodeSchool/learnyounode/03.first-io.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

Sin embargo al correr `learnyounode verify 03.first-io.js`el resultado fue el correcto. Estuve un rato probando a ver cuál era el error hasta que se me ocurrió probar la verificación.

**Comment by JuanCrg90** [comment]
`TypeError: path must be a string`

prueba pasandole el argumento `[2]`

`node 03.first-io.js texto.txt`

o con la ruta absoluta

`node 03.first-io.js /..../...../texto.txt`
